---

# Default Ansible user
# change this if you use a non-root user for running Ansible playbooks
ansible_system_user: root

# EPEL Repository for extra packages
epel_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

##########
## Subnet for Env and Domain, pass env as extra variable to playbook run command
#########
subnet: 108
env: stg 
domain: localdomain

##
## Provide IP address only for master node for sentinel configuration
##
master_node: x.x.x.x
masterauthpwd: inputpasswordhere 
clientauthpwd: inputpasswordhere 
cluster_name: redis-{{ env }}-cluster 
vipaddress: x.x.x.x
data_dir: /redis1/data
